[package]
name = "raya-test"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Test framework for Raya"

[dependencies]
raya-core = { workspace = true }
